spring.application.name=Studentdemo

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdemo
spring.datasource.username=postgres
spring.datasource.password=officialMY123.

spring.jpa.hibernate.ddl-auto=update